multi-draw:
  quantity: 10

packs:
  - ==: Pack
    items:
      - ==: org.bukkit.inventory.ItemStack
        v: 3218
        type: DIAMOND
    rarity: r
    id: 1
  - ==: Pack
    items:
      - ==: org.bukkit.inventory.ItemStack
        v: 3218
        type: WOODEN_AXE
        amount: 2
    rarity: c
    id: 2

rarities:
  - ==: Rarity
    shortname: c
    name: common
    probability: 40
  - ==: Rarity
    shortname: uc
    name: uncommon
    probability: 25
  - ==: Rarity
    shortname: r
    name: rare
    probability: 20
  - ==: Rarity
    shortname: sr
    name: super rare
    probability: 10
  - ==: Rarity
    shortname: ur
    name: ultra rare
    probability: 5
