multi-draw:
  quantity: 10

packs:
  - id: 1
    item: DIAMOND
    quantity: 10
    rarity: ur

rarities:
  - shortname: c
    name: common
    probability: 40
  - shortname: uc
    name: uncommon
    probability: 25
  - shortname: r
    name: rare
    probability: 20
  - shortname: sr
    name: super rare
    probability: 10
  - shortname: ur
    name: ultra rare
    probability: 5