name: CustomizableGacha
version: 1.0.0
main: be.julienbastin.customizablegacha.CustomizableGacha
description: Plugin to create customizable gacha draws
author: bastinjul (Julien Bastin)
website: https://julienbastin.be
api-version: 1.19
depend:
  - Vault
softdepend:
  - Vault
permissions:
commands: